### ISSUE TITLE
Привести структуру проекта в соответствии с правилами

### ISSUE THREAD

**Issue by AlexandrYZ** [Nikassa/Vaccine_accounting#1]
Структура описана в базе знаний [Структура](https://kb.pkzdrav.ru/pages/viewpage.action?pageId=9338906)

**Comment by Nikassa** [comment]
Привела к структуре папки и описание коммита.
Два дополнительных файла остались в корне:
- без pom.xml проект не соберется;
- .gitignore сам себя не добавляет.
